# Generated by Django 3.1.6 on 2021-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0002_auto_20210709_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('age', models.CharField(default='', max_length=255, verbose_name='Idade')),
                ('sex', models.CharField(default='', max_length=255, verbose_name='Sexo')),
                ('birth', models.DateField(verbose_name='Nascimento')),
                ('doc', models.IntegerField(default=0, verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Idade')),
                ('phone', models.ImageField(upload_to='', verbose_name='Telefone')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(default='', max_length=255, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
