# Generated by Django 3.1.6 on 2021-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='doc',
            field=models.CharField(default='0', max_length=255, verbose_name='Documento'),
        ),
    ]
