# Generated by Django 3.1.6 on 2021-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0004_auto_20210709_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=255, verbose_name='Telefone'),
        ),
    ]
