# Generated by Django 3.2.7 on 2021-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0005_auto_20210709_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tipoReligiao',
            field=models.CharField(default='', max_length=255, verbose_name='Religião'),
        ),
        migrations.AddField(
            model_name='person',
            name='tipoSindicato',
            field=models.CharField(default='', max_length=255, verbose_name='Sindicato'),
        ),
        migrations.AlterField(
            model_name='lgpdrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacyrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
