# Generated by Django 3.2.7 on 2021-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0006_auto_20211127_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='senhaDoUsuario',
            field=models.CharField(default='', max_length=255, verbose_name='Senha do usuário'),
        ),
    ]
