# Generated by Django 3.2.7 on 2021-11-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0007_person_senhadousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='doc',
            new_name='rg',
        ),
    ]
