# Generated by Django 3.2.7 on 2021-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0008_rename_doc_person_rg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rg',
            new_name='doc',
        ),
    ]
