# Generated by Django 3.2.7 on 2021-12-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0010_auto_20211201_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgpdrequest',
            old_name='tipo',
            new_name='type',
        ),
    ]
