# Generated by Django 3.2.7 on 2021-12-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0012_auto_20211201_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpdrequest',
            name='type',
            field=models.CharField(choices=[('CONFIRMAR TRATAMENTO', 'Confirmar tratamento'), ('ACESSAR DADOS PESSOAIS', 'Acessar dados pessoais'), ('CORRIGIR DADOS', 'Corrigir dados'), ('SOLICITAR ANONIMIZAÇÃO', 'Solicitar anonimização'), ('SOLICITAR PORTABILIDADE ', 'Solicitar portabilidade'), ('SOLICITAR ELIMINAÇÃO DE DADOS', 'Solicitar eliminação de dados'), ('OBTER INFORMAÇÕES SOBRE O COMPARTILHAMENTO', 'Obter informações sobre o compartilhamento'), ('REVOGAR CONSENTIMENTO ', 'Revogar consentimento')], default='CONFIRMAR TRATAMENTO', max_length=500, verbose_name='Tipo'),
        ),
    ]
