# Generated by Django 3.2.7 on 2021-12-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0013_alter_lgpdrequest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgpdrequest',
            name='type',
        ),
    ]
